package Model;
// Generated 23-sep-2017 15:00:09 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Users generated by hbm2java
 */
@Entity
@Table(name="USERS"
    ,catalog="VoxPopuli"
)
public class Users  implements java.io.Serializable {


     private String email;
     private String firstName;
     private String lastName;
     private boolean isAdmin;
     private String PWord;
     private boolean validPassword;

    public Users() {
    }

    public Users(String email, String firstName, String lastName, boolean isAdmin, String PWord, boolean validPassword) {
       this.email = email;
       this.firstName = firstName;
       this.lastName = lastName;
       this.isAdmin = isAdmin;
       this.PWord = PWord;
       this.validPassword = validPassword;
    }
   
     @Id 

    
    @Column(name="Email", unique=true, nullable=false)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="First_Name", nullable=false, length=60)
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    
    @Column(name="Last_Name", nullable=false, length=60)
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    
    @Column(name="Is_Admin", nullable=false)
    public boolean isIsAdmin() {
        return this.isAdmin;
    }
    
    public void setIsAdmin(boolean isAdmin) {
        this.isAdmin = isAdmin;
    }

    
    @Column(name="P_Word", nullable=false, length=46)
    public String getPWord() {
        return this.PWord;
    }
    
    public void setPWord(String PWord) {
        this.PWord = PWord;
    }

    
    @Column(name="Valid_Password", nullable=false)
    public boolean isValidPassword() {
        return this.validPassword;
    }
    
    public void setValidPassword(boolean validPassword) {
        this.validPassword = validPassword;
    }




}


